### PR TITLE
Docker client returns invalid json

### PR DESCRIPTION
**Pull request by chekunkov**
Workaround for docker-py issue https://github.com/docker/docker-py/issues/1059 - line can contain multiple json objects separated by `\r\n`

### CODE REVIEW

**Comment by vshlapakov** [comment]
@chekunkov The changes looks good, but have you encountered with the issue by yourself? If yes - was it a json parsing error or what? Asking because `json` library handles such rows pretty fine even with trailing CRLFs, that's this bug is transparent for us. Am I missing something and it really deserves such workaround?
```
>>> json.loads('{"status":"Pulling from library/ubuntu","id":"12.04"}\r\n')
{u'status': u'Pulling from library/ubuntu', u'id': u'12.04'}
```

**Comment by chekunkov** [comment]
@vshlapakov the issues is that 1 line can contain multiple json objects separated by `\r\n` - you can see an example of such line in a test case https://github.com/scrapinghub/shub-image/pull/12/files#diff-87010571bbeeee0b9a13279c493670f3R96

I've encountered it personally, it raises ValueError:

```
ValueError: Extra data: line 2 column 1 - line 9 column 1 (char 53 - 550)
```

**Comment by chekunkov** [comment]
From my first debugging session:

```
> /Users/alex/.virtualenvs/scrapy-demo/lib/python2.7/site-packages/shub_image/build.py(48)build_cmd()
-> import pdb; pdb.set_trace()
(Pdb) !line
'{"status":"Pulling from library/python","id":"2.7"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"5c90d4a2d1a8"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"ab30c63719b1"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"c6072700a242"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"abb742d515b4"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"7663bd2e167e"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"b68f5aeb12b3"}\r\n{"status":"Pulling fs layer","progressDetail":{},"id":"a0ff23346326"}\r\n'
```

**Comment by vshlapakov** [comment]
Got it, thanks for the patch and for the clarifications!

**Pull request merged**
